
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_none --extra_args vllm=True completions=False
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode generate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_none --force --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_none.csv" 
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_cfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_cfl.csv" > test_deepseek_cfl.log
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_scaffold_min --force --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_scaffold_min.csv" > test_deepseek_scaffold_min.log
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_recovery --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_recovery.csv" > test_deepseek_recovery.log


# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode generate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_none --extra_args vllm=True completions=False

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_dfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_dfl.csv" > test_deepseek_dfl.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_cfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_cfl.csv" > test_deepseek_cfl.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_scaffold --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_scaffold.csv" > test_deepseek_scaffold.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_recovery --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_recovery.csv" > test_deepseek_recovery.log
