# round 0
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt generic --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/none --timeout 55 --force --extra_args vllm=True reasoning_effort="high" completions=False
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode test --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt generic --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/none --timeout 55 --extra_args vllm=True reasoning_effort="high" completions=False
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode evaluate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt generic --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/none --timeout 55 --extra_args vllm=True reasoning_effort="high" completions=False

# round 1

LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim --timeout 55 --extra_args vllm=True completions=False reasoning_effort="high" completions=True trace_csv="./new_interventions/prelim/openai-gpt-oss-120b_high_all_prelim_intervention.csv"
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode test --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim --timeout 55 --extra_args vllm=True completions=False reasoning_effort="high" completions=True trace_csv="./new_interventions/prelim/openai-gpt-oss-120b_high_all_prelim_intervention.csv"
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode evaluate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim --timeout 55 --extra_args vllm=True completions=False reasoning_effort="high" completions=True trace_csv="./new_interventions/prelim/openai-gpt-oss-120b_high_all_prelim_intervention.csv"
pipenv run python src_extra/gather_all_files.py new_interventions/prelim/overall_results_openai-gpt-oss-120b_1.0_openapi_none_high.json 1.0 -s new_interventions/prelim/ --target-dir new_interventions/prelim --reasoning-suffix high -v
pipenv run python src_extra/gather_traces_into_csv.py --json_file 'new_interventions/prelim/overall_results_openai-gpt-oss-120b_1.0_openapi_none_high.json' --target_dir 'new_interventions/prelim' --models 'openai-gpt-oss-120b_high'
# cd new_interventions/
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/final_enumerate --timeout 55 --extra_args vllm=True reasoning_effort="high" completions=True trace_csv="./new_interventions/final_enumerate/openai-gpt-oss-120b_high_all_final_enumerate_intervention.csv"
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode test --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/final_enumerate --timeout 55 --extra_args vllm=True reasoning_effort="high" completions=True trace_csv="./new_interventions/final_enumerate/openai-gpt-oss-120b_high_all_final_enumerate_intervention.csv"
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode evaluate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/final_enumerate --timeout 55 --extra_args vllm=True reasoning_effort="high" completions=True trace_csv="./new_interventions/final_enumerate/openai-gpt-oss-120b_high_all_final_enumerate_intervention.csv"
# pipenv run python src_extra/gather_all_files.py new_interventions/final_enumerate/overall_results_openai-gpt-oss-120b_1.0_openapi_none_high.json 1.0 -s new_interventions/final_enumerate/ --target-dir new_interventions/final_enumerate --reasoning-suffix high -v
# pipenv run python src_extra/gather_traces_into_csv.py --json_file 'new_interventions/final_enumerate/overall_results_openai-gpt-oss-120b_1.0_openapi_none_high.json' --target_dir 'new_interventions/final_enumerate' --models 'openai-gpt-oss-120b_high'
# # cd new_interventions/
# python look.py
# cd ..
# pipenv run python src_extra/reasoning_rewrite/extract_and_add_suffix.py --type scaffold
# The above adds scaffold interventions to the CSVs


# round 2
pipenv run python src_extra/reasoning_rewrite/extract_and_add_suffix.py --type  scaffold
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim_scaffold --timeout 55 --force --extra_args vllm=True completions=True reasoning_effort="high" trace_csv="./new_interventions/prelim_scaffold/openai-gpt-oss-120b_high_all_prelim_scaffold_intervention.csv"
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode test --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim_scaffold --timeout 55 --extra_args vllm=True completions=True reasoning_effort="high" trace_csv="./new_interventions/prelim_scaffold/openai-gpt-oss-120b_high_all_prelim_scaffold_intervention.csv"
LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode evaluate --n_samples 5 --temperature 1.0 --spec_type openapi --safety_prompt none --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./new_interventions/prelim_scaffold --timeout 55 --extra_args vllm=True completions=True reasoning_effort="high" trace_csv="./new_interventions/prelim_scaffold/openai-gpt-oss-120b_high_all_prelim_scaffold_intervention.csv"


# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode generate --n_samples 1 --temperature 1.0 --spec_type openapi --safety_prompt specific     --max_concurrent_runs 16 --envs Python-Django --results_dir ./intervention_test_none --timeout 55 --extra_args vllm=True completions=False reasoning_effort="high"
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-120b --mode evaluate --n_samples 1 --temperature 1.0 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-Django Python-Flask Python-aiohttp Python-FastAPI --results_dir ./intervention_test_none --timeout 55 --extra_args vllm=True completions=False reasoning_effort="high"

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode generate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_none --force --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_none.csv" 
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_cfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_cfl.csv" > test_deepseek_cfl.log
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_scaffold_min --force --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_scaffold_min.csv" > test_deepseek_scaffold_min.log
# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models deepseek-ai/DeepSeek-R1-0528-Qwen3-8B --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_recovery --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_recovery.csv" > test_deepseek_recovery.log


# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode generate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_none --extra_args vllm=True completions=False

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_dfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_dfl.csv" > test_deepseek_dfl.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_cfl --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_cfl.csv" > test_deepseek_cfl.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_scaffold --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_scaffold.csv" > test_deepseek_scaffold.log

# LOCAL_API_BASE=http://localhost:8000 pipenv run python src/main.py --models openai/gpt-oss-20b --mode evaluate --n_samples 1 --temperature 0.001 --spec_type openapi --safety_prompt specific --max_concurrent_runs 16 --envs Python-aiohttp Python-Flask Python-Django Python-FastAPI --results_dir ./intervention_test_recovery --extra_args vllm=True completions=True trace_csv="./all_output_collate/deepseek-ai-DeepSeek-R1-0528-Qwen3-8B-None_reasoning_rewrites_recovery.csv" > test_deepseek_recovery.log
